[package]
name = "day02"
version = "1.0.0"
edition = "2024"

[dependencies.image]
version = "0.25.8"
optional = true
default-features = false
features = ["png"]

[features]
default = []
save-image = ["dep:image"]
